In [1]:
import numpy as np

 1. Broadcasting

In [2]:
# a Add a 1D array `[1, 2, 3]` to each row of a 2D array `[[10, 20, 30], [40, 50, 60]]`.
arr2d = np.array([[10, 20, 30], [40, 50, 60]])
arr1d = np.array([1, 2, 3])
result1a = arr2d + arr1d
print("a) Result:\n", result1a)
# b Multiply a 2D array `[[1, 2], [3, 4]]` by a 1D array `[10, 20]` column-wise.
arr2d_b = np.array([[1, 2], [3, 4]])
arr1d_b = np.array([10, 20])
result1b = arr2d_b * arr1d_b[:, np.newaxis]
print("b)\n", result1b)

a) Result:
 [[11 22 33]
 [41 52 63]]
b) Result:
 [[10 20]
 [60 80]]


 2. Indexing and Slicing (High Dimensional Arrays)

In [3]:
arr = np.arange(1, 25).reshape(2, 3, 4)
# a) Extract the second slice along axis 0.
result2a = arr[1]
print("a)\n", result2a)
# b) Extract all rows and the last column for all slices.
result2b = arr[:, :, -1]
print("b)\n", result2b)
# c) Reverse the order of slices along axis 0.
result2c = arr[::-1]
print("c)\n", result2c)
# d) Set all even elements in the array to -1.
arr_even = arr.copy()
arr_even[arr_even % 2 == 0] = -1
print("d)\n", arr_even)

a) Result:
 [[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
b) Result:
 [[ 4  8 12]
 [16 20 24]]
c) Result:
 [[[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
d) Result:
 [[[ 1 -1  3 -1]
  [ 5 -1  7 -1]
  [ 9 -1 11 -1]]

 [[13 -1 15 -1]
  [17 -1 19 -1]
  [21 -1 23 -1]]]


3. np.repeat

In [4]:
# a) Given `arr = np.array([1, 2, 3, 4, 5, 6])`, create a new array where every odd element is repeated twice.
arr3a = np.array([1, 2, 3, 4, 5, 6])
result3a = np.repeat(arr3a, np.where(arr3a % 2 != 0, 2, 1))
print("a)\n", result3a)
# b) Given `arr = np.array([1, 2, 3, 4, 5, 6])`, create a new array where elements are repeated based on their value.
arr3b = np.array([1, 2, 3, 4, 5, 6])
result3b = np.repeat(arr3b, arr3b)
print("b)\n", result3b)


a) Result:
 [1 1 2 3 3 4 5 5 6]
b) Result:
 [1 2 2 3 3 3 4 4 4 4 5 5 5 5 5 6 6 6 6 6 6]


4. Normalizing

In [5]:
# a) Normalize a 1D array `arr = np.array([10, 20, 30])` to have values between 0 and 1.
arr4a = np.array([10, 20, 30])
result4a = (arr4a - arr4a.min()) / (arr4a.max() - arr4a.min())
print("a)\n ", result4a)


a) Result:
  [0.  0.5 1. ]


5. Bonus Challenge

In [7]:
# a) Create a 3x3 matrix where each element at position (i, j) is i * j.
i = np.arange(3)
j = np.arange(3)
result5a = np.outer(i, j)
print("a)\n", result5a)
# b) Given a 4x4 matrix, replace all elements on the main diagonal with 0 without using a loop.
arr5b = np.arange(1, 17).reshape(4, 4)
np.fill_diagonal(arr5b, 0)
print("b)\n ", arr5b)

a)
 [[0 0 0]
 [0 1 2]
 [0 2 4]]
b)
  [[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]
